Repository urfu-2017/team6, pull requests merged in 2018-04, with the labels that each got.

#35 css-loader & up dependency & uglifyjs
  README.md
  next.config.js
  package-lock.json
  package.json
  pages/login/index.js
  pages/login/login.css
  pages/main/index.js
  pages/main/main.css
  server/routes/auth.js
Labels: backend, frontend

#36 Models changes
  models/Chat.js
  models/ChatInfo.js
  models/UserProfile.js
  server/controllers/chats.js
  server/controllers/profile.js
  server/routes/api.js
Labels: backend

#37 Messages API
  models/Chat.js
  models/Message.js
  pages/main/index.js
  server/api/hrudb.js
  server/api/messages/index.js
  server/controllers/messages.js
  server/routes/api.js
Labels: backend

#38 Messages clustering
  models/Event.js
  models/Message.js
  package.json
  server/api/hrudb.js
  server/api/messages/index.js
  server/controllers/messages.js
  server/routes/api.js
Labels: backend

#39 33 : redux & redux-saga with next.js
  .eslintrc
  actions/userActions.js
  components/Body.js
  package-lock.json
  package.json
  pages/main/index.js
  pages/main/main.css
  reducers/index.js
  reducers/sessionReducer.js
  sagas/index.js
  store/index.js
Labels: frontend

#40 Sockets integration
  api/index.js
  components/Body.js
  models/SocketEvent.js
  package-lock.json
  package.json
  sagas/index.js
  sagas/sessionSagas.js
  server/api/chats/index.js
  server/api/messages/index.js
  server/api/user/index.js
  server/controllers/chats.js
  server/controllers/messages.js
  server/controllers/profile.js
  server/routes/api.js
  server/server.js
  server/socket/index.js
  store/index.js
Labels: backend

#45 business logic: sagas, reducers, actions
  actions/chatsActions.js
  actions/contactsActions.js
  actions/messagesActions.js
  actions/userActions.js
  api/index.js
  models/Chat.js
  reducers/chatsReducer.js
  reducers/contactsReducer.js
  reducers/index.js
  reducers/messagesReducer.js
  reducers/sessionReducer.js
  sagas/chatsSagas.js
  sagas/contactsSagas.js
  sagas/index.js
  sagas/messagesSagas.js
  sagas/sessionSagas.js
  server/api/hrudb.js
  server/api/messages/index.js
  server/controllers/chats.js
  server/controllers/messages.js
  server/controllers/profile.js
  server/routes/api.js
Labels: backend, frontend

#47 Meta
  api/index.js
  package-lock.json
  package.json
  server/api/messages/index.js
  server/controllers/messages.js
  server/routes/api.js
  utils/metaparse.js
Labels: backend, frontend
